Repository gisat-panther/test-package, pull requests merged in 2020-08, with the labels that each got.

#34 minor change
  index.js
Labels: major

#35 minor change 2
  .github/workflows/tag-validation.yml
  CHANGELOG.md
  index.js
  package-lock.json
  package.json
Labels: patch

#36 Devdev
  .autorc
  .github/workflows/release.yml
  index.js
Labels: major

#37 Another dev branch test
  index.js
Labels: minor

#38 Another dev branch test 2
  index.js
Labels: patch

#39 Another dev branch test - versions/labels
  index.js
Labels: patch
